### ISSUE TITLE
Planned changes

### ISSUE THREAD

**Issue by christianalfoni** [christianalfoni/webpack-bin#10]
- [x] Information about repo and creating issues
- [x] Describe how the project works in the README
- [x] Do not create BIN until first save (coming from root url)
- [x] Implement Live Sharing
- [x] Better handling of when to show loader, should be time based
- [x] Add timestamp to bins
- [x] Add timestamp to in-memory bundles and clean up process
- [x] Add Cerebral, Redux, CycleJS (Angular2 has a crazy setup of packages)
- [x] Add Sass loader
- [x] Add Less loader
- [x] Display text about `bin.log()` when no logs
- [x] Delete files
- [x] Implement console using global `bin.log` in javascript to log out values. Want to keep normal console.log behaviour. Will also log out JavaScript errors
- [x] Change to `ts-loader`
- [x] Twitter share
- [ ] Embed bin
- [ ] Add TypeScript linter (https://github.com/basarat/TypeScriptEditor)
- [x] Download app with package.json, webpack deps and files
- [x] Google Analytics
- [x] Increase session duration to 24 hours
- [x] Improve responsive experience
- [x] Add loader when launching app
- [ ] Allow log to be shown below preview (http://alexkuz.github.io/react-dock/demo/)
- [x] Always allow LIVE, just start up a new BIN first, if not currently owner
- [x] Add HTML highlighting and linter
- [x] Add raw loader for HTML and TXT
- [x] Add json loader, highlighter and linter
- [x] Add better initial boilerplate with css and HTML
- [ ] Bring back decorator

**Comment by bogas04** [comment]
Really looking forward to 
- [ ]  Download app with package.json, webpack deps and files

Any tips on how to work on it ?

**Comment by christianalfoni** [comment]
Yeah, a colleague of mine came up with the idea :)

It should not be problematic. Just have to create a zip on the server based on files from the in-memory file system and some custom files. Should probably add `webpack-dev-server` too.

But I think I got the code sharing up and running now so I thought I would do this part next :)

**Comment by bogas04** [comment]
Alright. BTW I was wondering if this can be served as an Electron app too, i.e. sort of offline support.

**Comment by christianalfoni** [comment]
Hm, that would require a lot more efforts. Not sure if it gives enough value taking into account the time it takes to build it. Lets put up the download project stuff first and see where we stand :-)
