### ISSUE TITLE
cycle JS boilerplate will not load

### ISSUE THREAD

**Issue by SteveALee** [christianalfoni/webpack-bin#102]
Problem with live site. I tried to access the cyclesjs template http://www.webpackbin.com/VJBjp2yAg but got told I'can't load cyclels boilerplate 'You are the first to grab these NPM packages, it will take a few seconds..'' If I try again later I get told NPM packages 'still' being loaded.

**Comment by christianalfoni** [comment]
Its fixed :-)

**Comment by avanslaars** [comment]
I had an issue the other day trying to load RXjs... I wonder if Rx is the culprit here too? It is rather large.
