### ISSUE TITLE
angular2 ngModel error

### ISSUE THREAD

**Issue by rascada** [christianalfoni/webpack-bin#103]
angular2 don't work correctly

[demo](http://www.webpackbin.com/N1hlEDm0l)

``` ts
import {Component} from 'angular2/core';

@Component({
    selector: '#app',
    template: `
      <h1> {{ model }} </h1> 
      <input [(ngModel)]="model" placeholder="model" />`
})
export class AppComponent {
  model: string = 'test';
}
```

```
Uncaught EXCEPTION: Error during evaluation of "input" ORIGINAL EXCEPTION: TypeError: this.directive_0_1.onChange is not a function ORIGINAL STACKTRACE: TypeError: this.directive_0_1.onChange is not a function at t.ChangeDetector_AppComponent_0.handleEventInternal (viewFactory_AppComponent:261:36) at t.handleEvent (http://sandbox.webpackbin.com/api/sandbox/vendors/2246156992/bundle.js:6:14620) at t.triggerEventHandlers (http://sandbox.webpackbin.com/api/sandbox/vendors/2246156992/bundle.js:8:25083) at eval (viewFactory_AppComponent:330:110) at http://sandbox.webpackbin.com/api/sandbox/vendors/2246156992/bundle.js:12:27411 at http://sandbox.webpackbin.com/api/sandbox/vendors/2246156992/bundle.js:12:20197 at t.run (http://sandbox.webpackbin.com/api/sandbox/vendors/2246156992/bundle.js:8:9270) at HTMLInputElement.i (http://sandbox.webpackbin.com/api/sandbox/vendors/2246156992/bundle.js:12:20175) at t.invokeTask (http://sandbox.webpackbin.com/api/sandbox/vendors/2246156992/bundle.js:1:7615) at t.runTask (http://sandbox.webpackbin.com/api/sandbox/vendors/2246156992/bundle.js:1:4967) ERROR CONTEXT: [object Object]
```

**Comment by christianalfoni** [comment]
Does it work when you download the project and run it locally?

**Comment by rascada** [comment]
No, locally input value at least change to bounded model, but that's all.
Model don't react to input changes, don't throw error either.

**Comment by christianalfoni** [comment]
Hm, strange, but then I would suggest it is an Angular2 thing. Still Beta and I have just followed stackoverflow issues to build the boilerplate. could not find anything about zone.js and reflect-metadata in the Angular2 docs. Maybe we could find some boilerplate with webpack somewhere? Where we are sure it works, then copy that into webpackbin.

I am pretty confident it is not a webpackbin problem at least, since it does not work locally either.

You want to see if you could find a working boilerplate with webpack somewhere? Then you can try creating a bin manually and put it in here, and I will update it on the service :-)

**Comment by rascada** [comment]
Here is working webpack configuration - [ng2-webpack](https://github.com/rascada/ng2-webpack)
On [webpackbin](http://www.webpackbin.com/N1zrVj7Cx)
![image](https://cloud.githubusercontent.com/assets/10521222/14116850/1dc9a25c-f5e2-11e5-8796-431061b04f62.png)

**Comment by christianalfoni** [comment]
Yeah, the NPM extractor crashed :) I am making a fix for it now. Do not quite understand how it was able to extract the same packages twice. Did you install with different versions?

Making fix now and will check it :-)

**Comment by christianalfoni** [comment]
Thanks for building the BIN btw :)

**Comment by rascada** [comment]
No problem, thanks for great project! :D

I update zone.js in angular2 boilerplate from 0.6.2 to 0.6.6 trying to understand this weird behaviour :P

**Comment by christianalfoni** [comment]
Okay, so I got things running again now. Really great that I got to solve these things in the npm extractor, thank you for helping out! :)

That said, there is still an error, but this is definitely related to Angular2. I searched google a bit, even found an article, http://www.bennadel.com/blog/3007-failure-using-ngmodel-with-a-custom-component-in-angular-2-beta-1.htm, where the guy wrote lots about this thing and still can not figure it out :-)

**Comment by rascada** [comment]
I found `No value accessor for ''` exception in console

**Comment by rascada** [comment]
https://github.com/angular/angular/issues/7823

**Comment by christianalfoni** [comment]
Great @rascada , I turned off mangling and now it works :-)

**Comment by christianalfoni** [comment]
Btw, I have made a change in database and make your BIN the official boilerplate. Which means the new url will be:

http://www.webpackbin.com/angular2

**Comment by nirmalkumarvelupillai** [comment]
[http://www.webpackbin.com/VJ58pxqAb](http://www.webpackbin.com/VJ58pxqAb)
updated with angular2 final version and materialize css
