### ISSUE TITLE
The breakpoint to do anything is too wide.

### ISSUE THREAD

**Issue by crswll** [christianalfoni/webpack-bin#104]
I love this thing now but it took me way too long to realize it wasn't broken.

Can you add a notice that the browser needs to be at least 1281px wide to edit things? That or maybe lower the breakpoint a bit? I can try to get you a pull request if you'd like.

**Comment by christianalfoni** [comment]
Oh! good point :) Yeah, an indication that it is in "mobile mode" would be good. With some info on the resolution. But is it 1281? Should be 1280. That is indeed a bug

**Comment by crswll** [comment]
I double checked and it activates at 1280. I'm not sure why I thought 1281.

**Comment by dmitriid** [comment]
1280 is still too wide. There's more than enough space on lower widths. See jsbin for example.

Also reported in a dev chat:

> and here's me with tree style tabs so my viewport is always slightly narrower than normal
> so I fail to trip breakpoints all the time 

Also, the `configure` button disappears entirely in the mobile version

**Comment by laszlokorte** [comment]
Oh sorry I did not see this issue and created another one: https://github.com/christianalfoni/webpack-bin/issues/118

I agree the breakpoint should be lowered to something like 768px

**Comment by christianalfoni** [comment]
Hi guys, and thanks for the input.

The reason it stops at 1280 is because below that I need to implement responsive design and I hate working on responsive design. Its sooooo much work, time I could spend implementing features instead ;-)

The "below 1280" is now "mobile mode". Which means no code changes and configure is not something you can do anything with on mobile, so that is why it is removed.

But there was discussions on identifying mobile phones specifically, instead on window width. So planning to do that. But I am getting some help from a colleague now, who is more of a design guy, so hopefully he can help working on the responsiveness :)

**Comment by jfsiii** [comment]
I understand limiting behavior on a small screen, but 1280 is far from small or a mobile phone. I have a 13" MBP and have to put the window in Full Screen to edit. Merely resizing the window isn't enough to show the preview window.

This is awful UX. At a minimum, there should be some indication about what's going on. I thought the site was broken until I came here to file a ticket.

I don't view this as a "nice to have" feature, like editing on a phone. Not being able to edit on a 13" laptop is a bug. Not informing the user is a bug.

Also, you don't need to go fully responsive to make this un-broken on a laptop. As others have said, merely lowering the breakpoint (to 1200, 1000 or 768) would do it.

**Comment by christianalfoni** [comment]
That comment would have been a lot more useful if it was on a pull request containing the requested changes ;-)

**Comment by christianalfoni** [comment]
Sorry, I was tired yesterday, but it really sucks when I spend so many hours of my free time building such a large set of features and then get criticised for not prioritizing correctly. This is open source and we have to help each other create the best experience, not criticise the people spending all their free time on building something completely free to everyone.

I hope you take the time to convert your criticism to code and help me make this a good experience for everyone!

**Comment by neonsquare** [comment]
This is certainly something that is interesting to me. I may invest some time on that, but no promises here yet! I think using the pixel width as decision to restrict features is not ideal. I can understand that it may not be very comfortable to work on small mobile devices, but why should (simple) editing or managing files not be possible? The idea to create a (switchable) full screen preview is good - I think it would be enough to make a switchable layout between preview and (full) editing. This way the space is used in a more useful way and the app is still mostly unrestricted.

Switching between files could also be done using a drop down menu on narrow screens.

**Comment by jimthedev** [comment]
I'm working on a version that works better on smaller laptops and also allows editing on a phone by putting a the preview at the under the code so you can scroll to it. It isn't perfect but will be responsive.

**Comment by mxstbr** [comment]
@jimthedev is there any update on this or can I go ahead and work on this?

**Comment by jimthedev** [comment]
@mxstbr go for it.
