### ISSUE TITLE
Possibly bump the RxJS version in Cycle Boilerplate

### ISSUE THREAD

**Issue by avanslaars** [christianalfoni/webpack-bin#108]
I ran into a frustrating issue with code today that I finally traced to a difference in behavior between versions of Rx. When I load up the CycleJS boilerplate, it depends on Rx 2.4.10, and when I went to the current stable release (4.1.0) the issue went away... I'm not aware of any reason to run Cycle with an older version of Rx. Would it be possible to have a more current version loaded in that boilerplate?

**Comment by christianalfoni** [comment]
Ah! Sorry about that. It was probably related to a previous version where the SEMVER lookup was wrong. Boilerplate running with 4.1.0 now. Thanks so much for looking into it and reporting it :)
