### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'name' of undefined clientBuild.js:34

### ISSUE THREAD

**Issue by schotime** [christianalfoni/webpack-bin#12]
Frozen on "loading your webpackbin..." when selected a boilerplate to load (react cerebral). Had previously loaded redux fine.

**Comment by christianalfoni** [comment]
Did it work the second time around or is the problem there still?

**Comment by schotime** [comment]
It still occasionally happens. Can't find exact scenario. Will add more info if i find.

**Comment by christianalfoni** [comment]
Okay, great, thanks! I will add sourcemaps on next release to make more sense of the error.

**Comment by christianalfoni** [comment]
Closing this as sourcemaps are now in production. Let me know if it happens again :)
