### ISSUE TITLE
503 - main.js

### ISSUE THREAD

**Issue by icebob** [christianalfoni/webpack-bin#121]
Hello,

I got 503 Service Unavailable error for http://sandbox.webpackbin.com/main.js

My bin: http://www.webpackbin.com/N1fEr831W

**Comment by yordis** [comment]
@icebob can you verify because I clicked in your bin and everything seems to be fine for me. I don't get any 503

**Comment by christianalfoni** [comment]
Hm, there might have been a glitch there at some point. Hm, I do not have enough logging to figure it out. If you are able to provoke the issue I can look into it, or I will have to add more logging to figure this one out. Thanks for reporting :)

**Comment by icebob** [comment]
Yes, now it's working. If I see this error again, I will touch you.
