### ISSUE TITLE
Opening the console make the editor read-only

### ISSUE THREAD

**Issue by antoinerey** [christianalfoni/webpack-bin#123]
When you open the Chrome console, the whole editor becomes read-only. I dont know if that's an expected behaviour, but I that's quite disturbing.

**Steps to reproduce**
1. Create a new bin
2. Open the Chrome console
3. Try to type something

**Informations**
1. Chrome Version 49.0.2623.112 (64-bit)
2. OSX Version 10.11.3

I tried to reproduce this into Firefox and Safari, and I couldn't. It seems to be linked to Chrome only.

**Comment by christianalfoni** [comment]
Hi! Thanks for reporting. It might be because it goes into "mobile mode". This will be changed in next version. It has to do with the width of the screen :-)

**Comment by antoinerey** [comment]
Indeed, this is it. I didn't try to resize the console, but it works as normal when the console is not that large. 👍
