### ISSUE TITLE
Add ES7 class support

### ISSUE THREAD

**Issue by Ugarz** [christianalfoni/webpack-bin#129]
Hello,
I'm having some troubles in a project and decided to go on [webpackbin.com to make a starter kit](http://www.webpackbin.com/V1pCHPWWb) with es7 class support. But when I add this component I've got an unexpected token =. I can not modify the webpack configuration and I would like to use ES7.
Here a little more details :

``` javascript
import React from 'react';

class toto extends React.Component {
  myProp = 42;
  static myStaticProp = 21;

  constructor() {
    console.log(this.myProp); // Prints '42'
    console.log(toto.myStaticProp); // Prints '21'
  }
}
export default toto;
```

![video](https://cloud.githubusercontent.com/assets/6050079/14983689/0a26b4a6-113f-11e6-85b3-aed639f78832.gif)

I found some hints here on the [babel-preset-1](https://babeljs.io/docs/plugins/preset-stage-1/) containing a reference to [Class properties transform](http://babeljs.io/docs/plugins/transform-class-properties/) which is somehow related to my error :)

**Comment by christianalfoni** [comment]
Ah, yes, now it uses "preset-0". I can add more presets in next release to allow you to add that stuff :)

**Comment by Ugarz** [comment]
Thanks a lot @christianalfoni let me know if you need help :)
Your webpackbin is the clearest of bins I've tryied ! great work !

**Comment by christianalfoni** [comment]
Glad it has been helpful :-)

**Comment by Sharlaan** [comment]
As of 13/10/2016, i'm still getting linting error with class properties and ... operator.

Would be nice to see these ES7 features added to this very nice online bin.

Keep up the good work ! Cheers.

**Comment by santaclauze** [comment]
As of 13/03/2017, i'm still getting linting error. I am  trying to use static keyword.
Any work around, or config that can help?

**Comment by christianalfoni** [comment]
Hi guys,

You can turn off linting in the settings on the profile menu on the right :)

Since it is not official stuff the linters have not implemented it, can not do anything about that, sorry :(
