### ISSUE TITLE
Run loop on live

### ISSUE THREAD

**Issue by schotime** [christianalfoni/webpack-bin#13]
Just did a "live" feature test:
1. Loaded site and hit live.
2. Loaded cerebral-react booter
3. Second client connected
4. First client wrote out something to the bin.log
5. Clicked Run and looked at the log

It seems to get stuck in a loop. Almost like the run gets called on the second client which calls run on the first client which calls run on the second client etc. Disconnecting the second client fixes the loop issue on the first.

**Comment by schotime** [comment]
Further investigations have found that if you hit ctrl+s it works fine but when clicking run, it seems to click run on the other windows causing an endless loop. Probably need to disable the run button on other windows or call the signal directly? No idea hows its implemented so I'll leave it to you ;)

**Comment by christianalfoni** [comment]
Ah, thanks! Will check this as soon as I can :-)
