### ISSUE TITLE
Add support for HTML & CSS main (e.g. index.html & style.css)

### ISSUE THREAD

**Issue by jfsiii** [christianalfoni/webpack-bin#14]
I'd like to recreate the bins listed in https://twitter.com/JFSIII/status/704798099818958848 in webpack-bin but cannot because, afaict, there's no way to supply HTML or CSS to be used by the bin.

`import`ing from npm, and using other ES6 features is great but, IMO, no HTML or CSS files limits the utility.

**Comment by christianalfoni** [comment]
You can add CSS just by importing it :-)

``` js
require('./styles.css'); // This runs the webpack style loader, injects the css to the page
```

I have been thinking about attaching index.html there as well, its just that you rarely do anything with it and just takes up memory.

What you want to do in the index.html file?

I have to make it more clear how you import CSS. Not sure if people watches the intro movie. Maybe the initial BIN content should have a css file loaded

**Comment by christianalfoni** [comment]
Removed "Next Up" as I have to think about bringing in `index.html` some more. It causes some confusion because there is a special script loaded, which is the bundle. But opening up the `index.html` would mean that you would expect to load any file you create. This adds quite a bit of overhead in terms of implementation. And I think it would be confusing, as loading the `main.js` file directly would give a different result than using the webpack bundle. 

I could of course add something like:

``` html
<body>
  <!-- Load this file to use the bundle -->
  <script src="/api/sandbox/webpackbin_bundle.js" defer></script>
  <!-- Or load files directly
  <script src="/api/sandbox/main.js" defer></script>
  -->
</body>
```

Hm... it just do not feel right. And this service is not about solving everything. It is about solving the issue with using NPM packages and running a workflow. Adding an `index.html` is just not in that scope and it adds so much more work and possibly confusion.

**Comment by jfsiii** [comment]
Oh, right. I forgot about using Webpack's loader for CSS. Thanks.

In this case, I wanted the HTML to contain:

```
<form>
  <label><input type="radio" name="mode" value="multiples" checked> Multiples</label>
  <label><input type="radio" name="mode" value="stacked"> Stacked</label>
</form>
```

I'd like to have some control over the HTML available. Something more than just `<div id="app" />`.

**Comment by kentcdodds** [comment]
Agreed. Right now webpack bin works great for React or Angular 2, but for many other use cases it's kind of limited. I'm fine if you say that's scope creep though :-) Just some thoughts. I don't really have any solid use case myself. Just speculating about others.

**Comment by geddski** [comment]
I'd love an index.html file. Maybe make the parts of if that webpackbin inserts not editable (but still visible) and the user can add their own content to it.

**Comment by christianalfoni** [comment]
Great input here. Thanks :-)

But let me ask you this:

Do you want index.html or to add html? You can add html easily by just require an html file which loads to a string and you can insert it into #app tag. Or are there other things? :-)

**Comment by kentcdodds** [comment]
The workaround is simple enough with `innerHTML`, but it's not straightforward or simple/easy for beginners (line jsbin for example). If you don't care to "compete" with jsbin them that's fine, but if so then this is one barrier to lower I think.

**Comment by geddski** [comment]
@christianalfoni yeah it's just a convenience thing.

**Comment by christianalfoni** [comment]
Okay, thanks again :-) i completely see your point, so let's find a good solution. Just need to think a bit, will get back to this!

**Comment by christianalfoni** [comment]
Okay, I have implemented a solution I think works really well. Basically:
1. All bins starts with a typical `index.html` file
2. When you create a new file you can click a checkbox "Is entry"
3. When you now load this file with a script tag it will actually load the webpack bundle

That means you can load whatever you want as normal, but the file you set as "entry point" will be loaded as webpack bundle :-)

Will be part of Release 10
