### ISSUE TITLE
Keep preview / log pane in view

### ISSUE THREAD

**Issue by jfsiii** [christianalfoni/webpack-bin#15]
See http://www.webpackbin.com/N1jDrrvne where preview pane is push nearly off screen entirely because of a long line of text.

The biggest issue is that the split isn't resizable so the only way to get it into view is to wrap your code differently.

It'd be nice to have a reasonable `width` with `overflow: auto` or `scroll` on them so you could always read the output. In this case, the preview pane actually contained a helpful message but I couldn't see it.

**Comment by christianalfoni** [comment]
Yeah, I agree, let me add this to my list :-)

**Comment by jfsiii** [comment]
As of tag [`0.7.0`](https://github.com/christianalfoni/webpack-bin/releases/tag/v0.7.0) I cannot access the bin listed in the original issue.

See attached gif
![webpackbin intersitial blocks bin](https://cloud.githubusercontent.com/assets/57655/13614793/0be254f6-e527-11e5-8e78-8f1feb22a8e1.gif)

**Comment by Guria** [comment]
@jsfiii bins are not persisted yet, as I remember

**Comment by jfsiii** [comment]
@Guria, whoa. Is that right, @christianalfoni ? If so, is this behavior spelled out anywhere?

**Comment by christianalfoni** [comment]
Hi guys!

They are persisted, it is just your session that times out after 24 hours. 

There was an issue where the welcoming screen overrided, but that is fixed now :) Try again

**Comment by jfsiii** [comment]
Confirmed that I can access the bin again. Thanks, @christianalfoni.
