### ISSUE TITLE
Module not found: Error: Cannot resolve module 'react-tag-input'

### ISSUE THREAD

**Issue by prakhar1989** [christianalfoni/webpack-bin#160]
Hi Christian!

Thanks a lot for this excellent app! I was trying to set up a test bin with my personal package [react-tag-input](http://npmjs.org/packages/react-tag-input) but as soon as I hit save, I get the following error in the [bin](http://www.webpackbin.com/E11tUyI8Z)

```
ERROR: ModuleNotFoundError
Module not found: Error: Cannot resolve module 'react-tag-input' in /api/sandbox/14678070670465704
```

Any pointers as to where I'm going wrong? Thanks a ton :)

**Comment by bebraw** [comment]
Works for me. Did you add the package through the "configure" modal? You need to type its name to the project dependencies before you can import it.

**Comment by prakhar1989** [comment]
For some reason it works now. Weird. Thanks a lot =)
