### ISSUE TITLE
Improve displaying errors to users

### ISSUE THREAD

**Issue by jfsiii** [christianalfoni/webpack-bin#17]
When I first created a new bin, I couldn't figure out why it wasn't running. However, I couldn't even save it to post here because most of the buttons were disabled
<img width="1274" alt="screen shot 2016-03-07 at 9 01 48 pm" src="https://cloud.githubusercontent.com/assets/57655/13592527/dbb0d6ba-e4a7-11e5-8404-d45fd657f8e7.png">

I eventually found a linting error re: mixed spaces & tabs
<img width="1274" alt="screen shot 2016-03-07 at 9 00 02 pm" src="https://cloud.githubusercontent.com/assets/57655/13592535/ea649f20-e4a7-11e5-91cf-c6e16abf4cba.png">

and fixing that enabled the buttons
<img width="1272" alt="screen shot 2016-03-07 at 9 00 23 pm" src="https://cloud.githubusercontent.com/assets/57655/13592539/f3199a30-e4a7-11e5-9cb7-7489221bdfb6.png">

This behavior wasn't expected or obvious to me. It was only after scanning the file many times that I found the "error" (it's a style issue, not a language one).

Perhaps these should be displayed in a fixed position on the page (top or bottom) so they're more obvious to the user.

Is there a good reason to prevent running a bin because of a formatting issue?

Is there a way to control the rules & levels for the linter?

Is it a good idea to prevent saving the bin if there's an error? What if the "error" is a stylistic one?

**Comment by christianalfoni** [comment]
Actually, the linting was there due to missing errors from webpack. But as they are implemented now I can remove this limitation. Also prevents the UI from blinking.

Can not currently change the rules, but would be possible. That said. There should not be stylistic rules there. Only things that breaks the app. So probably have to review
