### ISSUE TITLE
Indicate when bin is "read-only"

### ISSUE THREAD

**Issue by TheSharpieOne** [christianalfoni/webpack-bin#171]
Note: Somewhat related to #104 
I wanted to point out that I have sadly never seen webpackbin before today (it seems like a very cool tool). I was linked to it in a GH issue for a code example of the issue. I tried to create a new bin, but could not... I could not figure out why this thing would not allow me to type.... turns out my browser window was too small (I don't max out / fullscreen my apps). I didn't realize this until I saw the youtube video showcasing the mobile feature.
With that in mind, there may want to be something that indicates that the bin is in a "read-only" mode (and maybe something informing the user to resize their browser to enable editing). Even to go as far as "popping" something when someone tries to type when they are not allowed.
Also, the Boilerplates button seems pointless, since you cannot edit the boilerplate at this point/window size.

**Comment by mxstbr** [comment]
Yeah this can be a bit confusing, I'd love for the mobile version to show somewhere it's read-only.
