### ISSUE TITLE
Add scrolling to Bundled Packages results

### ISSUE THREAD

**Issue by jfsiii** [christianalfoni/webpack-bin#18]
It's easy for the search results to overflow the menu/viewport height. The container should be scrollable.

Notice the difference between:

The search results as seen on my 13" laptop:
<img width="476" alt="screen shot 2016-03-08 at 11 25 03 am" src="https://cloud.githubusercontent.com/assets/57655/13613341/8af7e582-e520-11e5-90bd-a2110f198a4c.png">

Versus on my 27" Display
![screen shot 2016-03-08 at 11 25 20 am](https://cloud.githubusercontent.com/assets/57655/13613340/8adeaf86-e520-11e5-857d-8d782e084be0.png)

The laptop version doesn't show results for, say, the `react 15.0.0-rc.1, react-dom 15.0.0-rc-1` bundle which means it can't be used in bins.

**Comment by christianalfoni** [comment]
Wow, thanks! Will fix this!
