### ISSUE TITLE
Support adding npm package versions

### ISSUE THREAD

**Issue by jfsiii** [christianalfoni/webpack-bin#19]
Support specific versions of an npm packages. e.g. `d3@next` or `react@15.0.0-rc.1`.

This doesn't mean `import d3 from 'd3@next'`. Rather, some way to add packages at specific versions via the `Configure` menu.

**Comment by christianalfoni** [comment]
Actually, this worked earlier, you can `react@14.0.7` in the adder thingy there, but it seems to have broken with an other fix. WIll fix this :) And give a small notice of its possibility
