### ISSUE TITLE
Error message wanted if module not found

### ISSUE THREAD

**Issue by jkleiser** [christianalfoni/webpack-bin#2]
It would be nice to get an error message if module given in an import line was not found. Both of these lines have errors, but no error message is given:

```
import React from './react';
import HalloVerden from './HelloWorld';
```

The error in the first line is the './' before 'react'.

**Comment by jkleiser** [comment]
Another error type that does not give an error message, is if the component name is wrong, like here:

```
render(<BadWorld/>, document.querySelector('#app'));
```

**Comment by christianalfoni** [comment]
There has been done work to build errors now, so the first error there should now be shown in the preview window. The second though is just a plain javascript error which currently is only shown in your browser devtool console.

There will be implemented a custom console for WebpackBin though. Which will show any errors related to the JS code :)

**Comment by christianalfoni** [comment]
Webpackbin now has its own log, which notifies about JS errors
