### ISSUE TITLE
Support for jsxPragma in babel

### ISSUE THREAD

**Issue by idchlife** [christianalfoni/webpack-bin#21]
I can't see this option, but I think it will be kinda neat! There are several packages that uses jsx and are drop-in replacement for react (e.g. https://github.com/developit/preact). But they need one tweak for them:

```
query: {
      presets: ['es2015', 'stage-0'],
      plugins: [
        ['transform-react-jsx', { //this
          'pragma': 'h'
        }]
      ]
    },
```

**Comment by christianalfoni** [comment]
Great, thanks for the example, will definitely add this for next release :)

**Comment by idchlife** [comment]
@christianalfoni thank you! It will be really neat!
