### ISSUE TITLE
Application Error

### ISSUE THREAD

**Issue by arildwtv** [christianalfoni/webpack-bin#212]
<img width="563" alt="screen shot 2017-02-11 at 23 41 14" src="https://cloud.githubusercontent.com/assets/575067/22858068/a80ed37a-f0b3-11e6-8c3e-4276d97b4cd2.png">

The whole application seems to be down. Does this happen often? I'm teaching a React class and wanted to use webpackbin in the beginning to lower the threshold.

**Comment by Guria** [comment]
webpackbin 2  is coming soon:
https://github.com/cerebral/webpackbin/
https://webpackbin-test.firebaseapp.com/

**Comment by arildwtv** [comment]
Thanks for the info. I decided to use webpackbin in the class, and I think the students were happy with it. It crashed during the first assignment, but quickly got up on its feet again. After that, it worked perfectly. Can't wait for webpackbin2! It seems to have the features that I've sorely missed.
