### ISSUE TITLE
Trouble grabbing npm package '@cycle/dom'

### ISSUE THREAD

**Issue by bbarker** [christianalfoni/webpack-bin#219]
Each time I add this (currently detects version 14.3.0 of @cycle/dom) under Configure and the click Save, I'm told that I'm the first to grab this library, please wait, etc. However, it never finishes. If I reload the page, I'm back to where I was before trying to add this library, and trying to add it again results in a repeat of the same process. Adding other libraries works fine so far.

**Comment by bbarker** [comment]
I tried webpackbin2, e.g., https://webpackbin-test.firebaseapp.com/#/bins/-KdCT6ydKr2R9hBkgq3v

I can't grab any @cycle/whatever library, e.g., `@cycle/xstream-adapter`, I suspect because it can't handle the `@` symbol.

**Comment by christianalfoni** [comment]
It is actually the `/` causing it, the `@` prefix has logic to handle it. Anyways, need to url encode it first, will fix. Thanks for reporting :)

**Comment by christianalfoni** [comment]
@bbarker It is deployed now, if you want to try again :)

**Comment by christianalfoni** [comment]
Ah, wait, still issue... Firebase can not store `/` in their keys... why oh why does mr Staltz need all these special characters in his packages ;-)

Need to figure out how to solve that

**Comment by bbarker** [comment]
=( I'm a relative newcomer to the javascript world, so this suggestion may be ludicrous, but I noticed there is a package alias feature: https://www.npmjs.com/package/module-alias ; not sure if that might help or if there's an easier way.

**Comment by christianalfoni** [comment]
Okay, so I have deployed new version now @bbarker . It required quite a few fixes. Reason is that `/` fudges up urls and file paths... and Firebase keys. So need extra logic several places to make it work.... BUT! It should be working now :)

Thanks for following up on this!

**Comment by bbarker** [comment]
Awesome, thanks - I tried it, seems to work: https://webpackbin-test.firebaseapp.com/bins/-KdXjXHAYGIEo6lHO8QI 

Unrelated issue, the cycle libraries use debugging statements that write to console.log; I suppose there isn't an easy way to grab that output? I don't see it in the browser's console.log either. Feel free to direct me to report/discuss this elsewhere.

**Comment by christianalfoni** [comment]
@bbarker The new webpackbin repo is over here, so can continue there :) 

https://github.com/cerebral/webpackbin

I am not sure why I wanted to use `bin.log`, cause it does make more sense to just wrap `console.log`. Maybe you could write an issue on it? I can fix that :)
