### ISSUE TITLE
row files goes on to too many lines

### ISSUE THREAD

**Issue by faceyspacey** [christianalfoni/webpack-bin#220]
https://www.dropbox.com/s/3fns2o9jedia3c4/Screenshot%202017-02-22%2016.06.40.png?dl=0

I've seen it scrollable sometimes--perhaps that's the new version. But with the way it currently works, you quickly start losing vertical space on the page.

**Comment by faceyspacey** [comment]
@christianalfoni 

is there any way to control this? I've been working on a serious webpackbin to demonstrate my open source package, and I'm losing a lot of room on the page because file tabs dont horizontally scroll properly. Generally it's as simple as `overflow-x: scroll`. What can I do to help fix that?

**Comment by faceyspacey** [comment]
here's my bin by the way:

http://www.webpackbin.com/NJhKC9PFG

**Comment by christianalfoni** [comment]
@faceyspacey It is already fixed, will be deployed shortly :)

Though fixed in Webpackbin 2, https://github.com/cerebral/webpackbin ... will be released in 1-2 weeks.

**Comment by faceyspacey** [comment]
@christianalfoni  awesome! ..i dont see it on webpackbin.com though? did you mean it's only on the new version?

**Comment by faceyspacey** [comment]
It seems you were referring to the new webpack bin as it scrolls properly. If I copy my code to that bin, will it stick around as you finish it and as, I assume, it gets moved to webpackbin.com? I.e. if I save it now, do you plan to migrate these saved bins to www.webpackbin.com?

ps. an import feature would be nice, even if it only imported the files (e.g. from a downloaded webpackbin) and not the config.

**Comment by christianalfoni** [comment]
The production version of new webpackbin is at: https://webpackbin-prod.herokuapp.com , and will move to www.webpackbin.com in about a week. You can create your stuff there now if you want to :) It currently requires you to allow 3rd party cookies until it moves.

Import sounds nice, but complicated due to having to identify an entry point file, analyze loaders, packages etc. Even with just files it would need to identify en entry point. Has also been talk of importing GISTS. But yeah, it is for later, have to get current version into production first :)

**Comment by faceyspacey** [comment]
awesome...it says there is nothing at https://webpackbin-prod.herokuapp.com

**Comment by christianalfoni** [comment]
Sorry, `webpackbin-prod.firebaseapp.com` :)

**Comment by faceyspacey** [comment]
Thanks brother ...will you redirect URLs from there to webpackbin.com once its launched? 

...ps AMAZING PRODUCT BY THE WAY!

**Comment by christianalfoni** [comment]
Yeah :) I have implemented a warning about old urls on the new webpackin allowing you to go to old instance. Will run old instance for about a month I think.

Glad you like it! Pretty excited about the new release :)
