### ISSUE TITLE
downloaded package does not use index.html or configured entry

### ISSUE THREAD

**Issue by faceyspacey** [christianalfoni/webpack-bin#221]
When you download a package, it won't use the `index.html` file you created--only the original plain one. In addition, the webpack config file only uses `main.js` as the entry file, not another possibly different-named file.

**Comment by christianalfoni** [comment]
Thanks for reporting! Yes, this is definitely a bug, will fix it :)

**Comment by christianalfoni** [comment]
This should be fixed in the new production version now :)
