### ISSUE TITLE
How's webpack-bin different from wzrd.in?

### ISSUE THREAD

**Issue by jorgebucaran** [christianalfoni/webpack-bin#222]
@christianalfoni Hi, awesome project 👋. 

I was wondering, can you explain how is webpack-bin different from wzrd.in?

wzrd.in is marketed as _browserify-as-a-service_, so would it be accurate to say webpack-bin, or more specifically, [tree/master/server](https://github.com/christianalfoni/webpack-bin/tree/master/server), is _webpack-as-a-service_? 

Cheers!

**Comment by christianalfoni** [comment]
Good question :)

Webpackbin is more of a client than a service, but as you say, the "server" acts as the *webpack-as-a-service*. In Webpackbin 2, coming out in 1-2 weeks (https://github.com/cerebral/webpackbin), it will have *webpack-dll* and *webpack-sandbox* as separate services, which is more related to *wzrd.in* :) Where webpackbin is purely the client.

**Comment by jorgebucaran** [comment]
Exciting 1-2 weeks ahead then! Thanks for clarifying this for me.
