### ISSUE TITLE
Show log beneath preview window

### ISSUE THREAD

**Issue by christianalfoni** [christianalfoni/webpack-bin#23]
Initially toggle fullscreen or split, can add drag etc. later

**Comment by RamonGebben** [comment]
Do you have curtain flow idea's about this, you mention toggle full screen of split.
I assume you mean the full size of the preview, like it is currently and half preview and half log?

**Comment by christianalfoni** [comment]
Yeah, I think the best implementation now is to show the "full log" by default. Then give it a down arrow in the upper right corner, which makes it take half the space. Which changes arrow to up, to take full size again :)

Then we can later work on manually resizing it.

Also change full/half needs to resize the iframe as well. So log and iframe actually just takes half of the screen each. Or some percentage that makes sense

**Comment by RamonGebben** [comment]
So like this 
![image](https://cloud.githubusercontent.com/assets/5405406/13699246/7c3dfbfc-e779-11e5-8745-973752d80b6c.png)

**Comment by christianalfoni** [comment]
Yeah, exactly :-) :+1:

**Comment by christianalfoni** [comment]
Releasing this evening so implemented it :)
