### ISSUE TITLE
Module not found: Error: Can't resolve 'vuelidate/lib/validators'

### ISSUE THREAD

**Issue by ScreamZ** [christianalfoni/webpack-bin#231]
Hey,

for some reason can't import vuelidate :(

https://www.webpackbin.com/bins/-Kg9NT7oFQi1eGubcn8P

Does anyone knows why ?

Thanks

**Comment by christianalfoni** [comment]
@ScreamZ could you try importing `vuelidate/lib/validators/index` ? Webpackbin does not currently have logic to translate /index.js paths into directory, other than the entry point iself. Should fix that though... but yeah, please confirm :)

**Comment by ScreamZ** [comment]
@christianalfoni  Was this, nice catch ;)

https://www.webpackbin.com/bins/-Kg9XqY8rVXsOoZjrR1t

(Had to make another one bin because couldn't edit mine anymore)

Thanks buddy, keep the good job :)

**Comment by christianalfoni** [comment]
Okay, I fixed so that `folder/index.js` can be pointed to as `folder` now as well... so your previous code should work now :)

**Comment by ScreamZ** [comment]
@christianalfoni Thanks ! ;)
