### ISSUE TITLE
Completely broken for specific bin

### ISSUE THREAD

**Issue by levrik** [christianalfoni/webpack-bin#236]
Webpackbin seems completely broken for this bin: https://www.webpackbin.com/bins/-Kh6PKNXeRotZfnITGj7
Cannot edit, cannot click on anything.

Getting this in the console:
```
Uncaught TypeError: Cannot read property 'value' of undefined
    at Object.r [as function] (main.625ee67….js:1)
    at e.value (common.23b3aaa….js:1)
    at l (common.23b3aaa….js:1)
    at common.23b3aaa….js:1
    at e.value (common.23b3aaa….js:1)
    at l (common.23b3aaa….js:1)
    at common.23b3aaa….js:1
    at e.value (common.23b3aaa….js:1)
    at l (common.23b3aaa….js:1)
    at l (common.23b3aaa….js:1)
```

**Comment by christianalfoni** [comment]
@levrik Hi there,

This seems to be loader configuration related. I see that it relates to setting this state:

"app.currentBin.loaders"

What did you click in the loaders section of the configuration?

I see you have added all babel loaders... there might be some conflict there. Did you just click all of them and then it stopped working?

**Comment by levrik** [comment]
@christianalfoni This bin is not created by myself. It is the template for reporting issues of the `material-ui` project so I have no idea what is configured there.

**Comment by christianalfoni** [comment]
@levrik I also see it is a LIVE bin... meaning that it is for LIVE code sharing. I have removed some loaders and turned off LIVE bin... now it is working again. The owner of the BIN maybe had a presentation or something and forgot to copy the bin first.

I can note that LIVE bins should make a copy of the bin first :)

**Comment by levrik** [comment]
Thank you :)
