### ISSUE TITLE
Template literals highlighting

### ISSUE THREAD

**Issue by mariuslundgard** [christianalfoni/webpack-bin#238]
The syntax highlighter is not working correctly for template literals (ES2015):

![image](https://cloud.githubusercontent.com/assets/406933/25038829/f025806e-2100-11e7-8798-dc286e6d66e6.png)

PS. Great tool!

**Comment by christianalfoni** [comment]
Not supported in CodeMirror: https://github.com/codemirror/CodeMirror/issues/3026 :-(

But added string color to template literals at least (in next deploy)

**Comment by mariuslundgard** [comment]
https://github.com/atom/highlights

**Comment by christianalfoni** [comment]
Yeah, this will not work @mariuslundgard, cause it is codemirror that creates all the HTML. It needs to know everything that is going on to understand what line your are on, character etc. So codemirror has its own parsers. Sorry :(

**Comment by mariuslundgard** [comment]
Ah, makes sense, CodeMirror is not simply syntax highlighting, but a code editor 👍
