### ISSUE TITLE
Port the same example in cerebral and cycle

### ISSUE THREAD

**Issue by grigio** [christianalfoni/webpack-bin#29]
I think all the boilerplates should implement the redux counter example. So it's easier to compare them and pick the one more familiar

**Comment by christianalfoni** [comment]
If you want it faster it would be great if you create the BINs for these examples and send me the urls, I can just switch them around :-)

**Comment by christianalfoni** [comment]
Closing this, please reopen if you have suggestions on how these can look. Just give me urls and I can change them to boilerplates :)
