### ISSUE TITLE
Select/copy from text

### ISSUE THREAD

**Issue by jkleiser** [christianalfoni/webpack-bin#3]
It would be nice to be able to select and copy text from the .js and .css sources in the browser.

**Comment by christianalfoni** [comment]
It does not work? What browser are you on?

**Comment by jkleiser** [comment]
With the current version of WebpackBin I can select text, but on my screen it is difficult to see that something has been selected. The background color of the selection is just slightly darker than the background color of the surrounding text. The text I'm testing now is the "Welcome to WebpackBin". I'm testing with Safari 9.0.3 and Chrome 48 on Mac OS X.

**Comment by christianalfoni** [comment]
Ah, yeah, it is quite dark... let me fix that :-)

**Comment by christianalfoni** [comment]
Fixed :)
