### ISSUE TITLE
Configure menu displays under editor scrollbar

### ISSUE THREAD

**Issue by jfsiii** [christianalfoni/webpack-bin#31]
OS X 10.11.3 Observed in Safari, Firefox, Chrome (Stable & Canary)

<img width="1120" alt="screen shot 2016-03-09 at 8 30 24 am" src="https://cloud.githubusercontent.com/assets/57655/13642413/3ae79d9c-e5d1-11e5-942b-3dfae5741fcb.png">

**Comment by christianalfoni** [comment]
I believe this has been fixed in pull?

**Comment by jfsiii** [comment]
It appears fixed in Firefox, but remains in Chrome Stable & Canary, and Safari.

Tested with http://www.webpackbin.com/VkdRlq93g on OS X 10.11.3

**Comment by christianalfoni** [comment]
Ah, it is pulled in, though not released yet. Will keep open until deployed

**Comment by christianalfoni** [comment]
Ready for release
