### ISSUE TITLE
Add detach option in order to have mobile and VR friendly previews

### ISSUE THREAD

**Issue by Utopiah** [christianalfoni/webpack-bin#33]
I'm currently using JSBin to give webVR workshop. It allows to get instant feedback on ThreeJS project. The key advantage so far is that it allows to detach the output and thus load it on a mobile device then switch to VR mode.

**Comment by christianalfoni** [comment]
So this relates to #36 ?

**Comment by christianalfoni** [comment]
Please close if it is the same :)

**Comment by Utopiah** [comment]
Yes it's the same, only I wrote it earlier :p
