### ISSUE TITLE
Create Chat

### ISSUE THREAD

**Issue by RamonGebben** [christianalfoni/webpack-bin#39]
It would be great to ask you some question when we want to contribute.
 @christianalfoni could you open a [Gitter](https://gitter.im/) or [Slack](https://slack.com/) for this project?

**Comment by christianalfoni** [comment]
Join at Discord :) 

https://discord.gg/0sSDrySrvUYwRlZM

**Comment by RamonGebben** [comment]
Great thanks. You can close the issue then :)
