### ISSUE TITLE
Add Docker

### ISSUE THREAD

**Issue by RamonGebben** [christianalfoni/webpack-bin#40]
In order to make development and deployment easier I think it would be a great idea to add Docker.
This way we don't need to clutter our system with dependencies such as mongodb and we could guarantee that the project will run on any machine as long as Docker is installed.

**Comment by christianalfoni** [comment]
Hm, do not see any harm in this? As long as it does not add complexity for those not familiar with Docker... like me? :) How would this work exactly?

**Comment by RamonGebben** [comment]
I found [this guide](https://nodejs.org/en/docs/guides/nodejs-docker-webapp/) which walks you through the basics of setting it up. 

Then the only thing you would need to do when you want to start developing is start the docker image and your application will run in a contained environment. If you want to know more about how docker itself works, hit me up on the discord channel.

**Comment by guumaster** [comment]
I've just found this repo. I'm familiar with dockerized node services. I can give it a spin if you want.

**Comment by RamonGebben** [comment]
Please do, I was already planning on giving it a go on the weekend but if you want to be my guest :)

**Comment by guumaster** [comment]
I was able to create the service but I'm getting this error: 

```
webpackbin_1 | TypeError: req.session.middleware is not a function
webpackbin_1 |     at module.exports.getFile (/server/sandbox.js:81:19)
webpackbin_1 |     at Layer.handle [as handle_request] (/node_modules/express/lib/router/layer.js:95:5)
webpackbin_1 |     at next (/node_modules/express/lib/router/route.js:131:13)
webpackbin_1 |     at Route.dispatch (/node_modules/express/lib/router/route.js:112:3)
webpackbin_1 |     at Layer.handle [as handle_request] (/node_modules/express/lib/router/layer.js:95:5)
webpackbin_1 |     at /node_modules/express/lib/router/index.js:277:22
webpackbin_1 |     at param (/node_modules/express/lib/router/index.js:349:14)
webpackbin_1 |     at param (/node_modules/express/lib/router/index.js:365:14)
webpackbin_1 |     at Function.process_params (/node_modules/express/lib/router/index.js:410:3)
webpackbin_1 |     at next (/node_modules/express/lib/router/index.js:271:10)
```

@christianalfoni, Any ideas why I got that error? I'm running this commands: 

```
npm install
npm run build:client
npm run build:server

npm start
```

Anything missing?

@RamonGebben, this is my [`Dockerfile`](https://github.com/guumaster/webpack-bin/blob/feature/dockerized-service/Dockerfile)

**Comment by RamonGebben** [comment]
You are still missing some stuff, like mongo db I do not see the install steps for that, maybe we want to ensure that it's installed in the post install script.

And if I'm correct with that dockerfile we would need to rebuild every time we update front-end sources? Try to mount the front-end folder from the host system so that when you edit a source it will be updated inside the container as well.

**Comment by guumaster** [comment]
Check the `docker-compose.yml` file. I'm using a different service for that. When I get that error, mongo is up and running and I can see the example bin page. The error is thrown after hitting "run" button

**Comment by RamonGebben** [comment]
@guumaster I just checked out your branch and having trouble running the setup at all, shall we take this out of the issue and on to the discord channel?

@christianalfoni shared this invite URL in de different issue https://discord.gg/0sSDrySrvUYwRlZM.

**Comment by christianalfoni** [comment]
Hi guys, there is one thing missing from the README, I will add it now.

You have to setup your hosts file with: `www.webpackbin.dev` and use that instead of localhost. It has to do with cookies

**Comment by christianalfoni** [comment]
Got so much other stuff to look into, so closing this as I have no experience with Docker
