### ISSUE TITLE
Add support for decorators

### ISSUE THREAD

**Issue by bfitch** [christianalfoni/webpack-bin#43]
![screen shot 2016-03-09 at 11 45 15 pm](https://cloud.githubusercontent.com/assets/577208/13659609/27f89d50-e651-11e5-8538-7fc53142555e.png)

**Comment by christianalfoni** [comment]
Yeah, this is kinda annoying. I have to remove an important linting rule to make it work. Could of course implement this with the toggling of linting rules alltogether. So that we turn off linting when decorators plugin is activated. What you think?

**Comment by christianalfoni** [comment]
Still not sure what to do with this. Decorators are not supported yet, not in linters or Babel really. (own plugin). So yeah... really annoying. Pushing it for next release

**Comment by christianalfoni** [comment]
Think we will solve this by turning off the linter on #44
