### ISSUE TITLE
Reword "Current Package Bundle" input label

### ISSUE THREAD

**Issue by bfitch** [christianalfoni/webpack-bin#49]
It's not very obvious when using webpack bin for the first time that the "Current Package Bundle" search will search and install packages from the npm registry. I initially thought it would search for _existing_ packages in my current bundle. Perhaps rename it to "Search NPM packages:" and move "Current Package Bundle" underneath the search input (above the installed package list).

![screen shot 2016-03-09 at 11 58 35 pm](https://cloud.githubusercontent.com/assets/577208/13660018/81f1c6b2-e654-11e5-86ca-7211b8967eab.png)

Ah, just noticed that "Add NPM package..." is set as placeholder text. But, I still missed it the first few times using it...wasn't totally discoverable to me.

**Comment by christianalfoni** [comment]
I agree :-)
