### ISSUE TITLE
Mark modified files

### ISSUE THREAD

**Issue by gpaucot** [christianalfoni/webpack-bin#52]
For modified files but not yet saved, perhaps a star besides the name just to know what exactly runs. Then, when we save, the star would disappear.

Before:
![image](https://cloud.githubusercontent.com/assets/4678416/13663959/cf890692-e6a4-11e5-95b1-b532f92ee747.png)

After:
![image](https://cloud.githubusercontent.com/assets/4678416/13663986/083da592-e6a5-11e5-890b-8463285ee3bd.png)

Great project thanks !

**Comment by christianalfoni** [comment]
Good idea! Will add to list :-)
