### ISSUE TITLE
Add Angular boilerplate

### ISSUE THREAD

**Issue by corporateanon** [christianalfoni/webpack-bin#53]

**Comment by christianalfoni** [comment]
Great! Maybe you could create a bin and paste the URL here? Then I can convert it to an Angular boilerplate :)

**Comment by corporateanon** [comment]
Good idea. Why not)

**Comment by christianalfoni** [comment]
Super, just paste url here and I will make it part of next release :)

Remember that you can use .html files and require them as plain strings to use as templates

**Comment by corporateanon** [comment]
Can I add some non-standard webpack plugins? For example, `ng-cache-loader`.

**Comment by christianalfoni** [comment]
Sorry, can not do that. At least not at the moment. The reason is that loaders needs to be preloaded into the service and they all have different configuration which we need to implement in the UI of WebpackBin. But you can add an issue on it. Though cache loader seems like optimization? Maybe not needed on such a small demo?

Or create an issue and I will look into it as the project moves on :)

**Comment by corporateanon** [comment]
It is not an optimization. It is needed to load partials.

**Comment by christianalfoni** [comment]
Ah, I see, sorry. Then it needs to be added as a specific loader. Suggest we create a simple Angular boilerplate now and then we can change it when `ng-cache-loader` is added? I can add it on the `Release 10` if you create an issue on it :)

**Comment by corporateanon** [comment]
Ok, I am working at the simplest possible angular boilerplate.

**Comment by christianalfoni** [comment]
:+1:  Let me know when it is done and I will prepare, thanks!

**Comment by corporateanon** [comment]
One more thing. Is it possible to change index.tpl.html?
If not, I will have to use manual angular bootstrap, that is not a common practice.

**Comment by christianalfoni** [comment]
Currently no access to the index file. Just need some thinking time on it :) The reason is that webpackbin does some manipulation to the index file. So need a safe way to still allow that, but not show it in the bin or the downloaded zip.

But yeah, we will get there :)

**Comment by corporateanon** [comment]
Well, that's it
http://www.webpackbin.com/NJXd3A53g

**Comment by christianalfoni** [comment]
Good stuff! I will change the name to `angular` on release, thanks a bunch. You created an issue on ng-cache thingy? Can make that part of Release 10. The index stuff might get in on Release 10 or it will be part of Release 11

**Comment by corporateanon** [comment]
Turns out, we dont need ng-cache.
It is also not too much boilerplate (lines 7-11) if we don't change index.tpl.html.

So it's okay to leave it as it goes.

**Comment by corporateanon** [comment]
I have also noticed the problem with download. `raw-loader` is not included in `package.json` in the generated archive.
So the downloaded project requires manual installation ow the `raw-loader`.

**Comment by christianalfoni** [comment]
Ah, great stuff!

Ah, okay, add an issue on that bug instead then? Should be able to squeeze that in with `Release 9`. Thanks for testing! :)
