### ISSUE TITLE
What is the keyboard access

### ISSUE THREAD

**Issue by SteveALee** [christianalfoni/webpack-bin#55]
From the demo video you seemed to save with a key sequence. There only seems to be 'Run' on the UI

Can you document this and others? Perhaps use a ? key handler like google do?

**Comment by christianalfoni** [comment]
CTRL + S or CMD + S , is shortcuts for saving :) Will add a UI helper for this

**Comment by SteveALee** [comment]
Wouldn't it be better to get the key to agree with the button? 

Suggest changing Play button -> Save as I think that is better

**Comment by christianalfoni** [comment]
Yeah, let me change that :)
