### ISSUE TITLE
for cyclejs 'attribute' not needed

### ISSUE THREAD

**Issue by SteveALee** [christianalfoni/webpack-bin#56]
`input('.field', {type: 'text'}),` does as well assume {} = attribs and [] = children

**Comment by christianalfoni** [comment]
Oh, hehe, grabbed it from the Cycle JS site :) But will update this, thanks!

**Comment by christianalfoni** [comment]
Sorry, trying to be a bit better at delegating. If you want to create a new Cycle JS boilerplate please create a BIN and send me the link, I will update the boilerplate :)

**Comment by SteveALee** [comment]
Problem with live site. I tried to access the cyclesjs template http://www.webpackbin.com/VJBjp2yAg but got told I'can't load cyclels boilerplate 'You are the first to grab these NPM packages, it will take a few seconds..'' If I try again later I get told NPM packages 'still' being loaded.

**Comment by SteveALee** [comment]
I was wrong. Any members of the object do become become _properties_ of the DOM Node but there is not always a 1 to 1 mapping of _props_ to _attributes_. See cyclejs/core#82. Am closing.

**Comment by christianalfoni** [comment]
Oh, cool, thanks. I learned something new :)

**Comment by SteveALee** [comment]
me to - or perhaps I re learnt it - hehe

Steve Lee
OpenDirective http://opendirective.com
