### ISSUE TITLE
Add HTML source view of output

### ISSUE THREAD

**Issue by SteveALee** [christianalfoni/webpack-bin#57]
A view of the html source for the output would be very useful.
Plus link through to css files?

Of course you can use F12 and inspector picker but that is a little fiddly.

Suggest tabs for right hand pane

**Comment by SteveALee** [comment]
Anther approach would be to auto locate the root of the view in the F12 html tree and make it the current node

**Comment by christianalfoni** [comment]
Yeah, I am a bit in flux on how to handle the `index.html` file. The output is really not the output of the BIN. It is mixed with WebpackBin "helpers". Hitting "download" is how you really get a real view of how the HTML file looks.

And yeah, there is really nothing happening in the `index.html` file other than loading the webpack bundle of your BIN. So it is not very interesting either. Though I completely understand it is a black box now, which is a bit uncomfortable ;-)

**Comment by christianalfoni** [comment]
index.html file will be available on next release :-)
