### ISSUE TITLE
Vue.js boilerplate

### ISSUE THREAD

**Issue by icebob** [christianalfoni/webpack-bin#58]
I made a simple Vue.js hello world boilerplate.

http://www.webpackbin.com/NJlV7vc2l

**Comment by christianalfoni** [comment]
Sweet! Though I would suggest adding an HTML file and require it instead, as the template? WebpackBin supports loading HTML files as strings :)

I will add it nevertheless on next release

**Comment by icebob** [comment]
Great idea. I added html template files to bin. http://www.webpackbin.com/NJlV7vc2l

**Comment by christianalfoni** [comment]
eyh, that looks great! Will be part of next release, thanks :)
