### ISSUE TITLE
TypeScript entry point

### ISSUE THREAD

**Issue by m1gu3l** [christianalfoni/webpack-bin#59]
Looks like javascript entry point (main.js) is locked. Since TypeScript loader is available it makes sense to allow TypeScript entry point.

**Comment by RamonGebben** [comment]
@m1gu3l Im not familiar with how Typescript works, could you elaborate on what you mean? Is it manner of renaming the file extension or are there others steps required?

**Comment by m1gu3l** [comment]
Renaming the file extension should do. See https://github.com/TypeStrong/ts-loader example.

**Comment by RamonGebben** [comment]
@christianalfoni this should be fairly easy to solve right?

**Comment by christianalfoni** [comment]
Hi guys,

It is a bit work as WebpackBin is hardcoded to the `main,js` file. But when implementing the renaming of files I can make a fix for this as well. The thing is that a name change also requires the service to create a new bundle, as the entry point is changed. So have to know if the entry file has been changed etc... yeah, it is a bit more work than you might think, but will fix this :-)
