### ISSUE TITLE
False linting error in .babelrc

### ISSUE THREAD

**Issue by ahmed1490** [christianalfoni/webpack-bin#60]
<img width="578" alt="screenshot" src="https://cloud.githubusercontent.com/assets/623510/13686948/cf19c8d0-e718-11e5-80fd-0e91debddc7b.png">

**Comment by christianalfoni** [comment]
Hi there,

You do not configure webpack manually in webpackbin, you use the configurator :) You do not have access to everything, but more stuff is coming in the next releases. 

Hot reloading is not supported either and not sure if it will be. Hot module replacement is not built for multiple clients and will require a lot of rewrite to make it work. It is also most commonly only used with React and would make React work differently than everything else in regards of handling the Bin itself. So yeah, just insane amounts of work for very little value.

Sorry about that, but yeah... have to my efforts where it gives most value :-)

Will add issue on adding rest spread plugin!

**Comment by ahmed1490** [comment]
Hey,
Thanks for the quick response :)
So I wasn't trying to run anything there.

I am getting an error for hotreloading and I thought it would be a good idea to share my code snippets there.

Also since I am not intending to run it the first place, its kind of annoying when the overlay comes saying "setting up" or something like that. I wish that should be cancellable.

and oops, now it seems i put the application down. 

http://www.webpackbin.com/4kK7H1o2x

**Comment by ahmed1490** [comment]
Just to be clear,
I was reporting the false linting error on the left. Nothing to do with these setup :)

**Comment by christianalfoni** [comment]
Ah, I see! :-)

Let me set this issue as putting the default mode and linting to "nothing". So when files are not recognized it will not do any highlighting and linting :)

About not running the files is kinda counter intuitive to what the service tries to do :) If you just want to share some code I would suggest just creating a GIST on Github. Its not really what webpackbin was designed for.

The application is okay btw, no worries! :-)

**Comment by ahmed1490** [comment]
I know about gist.. :)
But Gist doesnt fare anywhere near this. I love the interface and it feels close to the editor experience with this.
its more like jsfiddle to me, where anyone can fork-update-save-share. Not sure if this upsets you seeing people using the platform use it in this manner.

Thank you! :D

**Comment by christianalfoni** [comment]
Hehe, actually I have just never really thought about it like that. If you want you could create a new issue to have a separate "save" button which does not run the code? Just saves the bin? Then things would be okay, right?
