### ISSUE TITLE
Add Babel rest spread plugin

### ISSUE THREAD

**Issue by christianalfoni** [christianalfoni/webpack-bin#61]

**Comment by rtsao** [comment]
Would it be better to simply include all the stage presets like the Babel 6 REPL (https://babeljs.io/repl/) rather than specifying individual plugins?

**Comment by christianalfoni** [comment]
Hm, though I do not think spread plugin is part of any of stage stuff? Though could add the rest of the stages as well :)

**Comment by rtsao** [comment]
`transform-object-rest-spread` is in stage 2: https://babeljs.io/docs/plugins/preset-stage-2/

**Comment by christianalfoni** [comment]
Ah, so it should already work then as stage-0 has all the other stages. But okay, will add stages on next release :-)

**Comment by christianalfoni** [comment]
You know, I do not see any reason to include stage 1 and 2, when we have stage 0. It is about use/learn what you want. Let me know if you have any arguments why we need stage 1 and 2, and I will book it for next release instead
