### ISSUE TITLE
Babel loader order: Stage-0 should be after ES2015 and react

### ISSUE THREAD

**Issue by productiveme** [christianalfoni/webpack-bin#65]
Getting a Linter error and ModuleBuildError : Missing class properties transform when trying to

```
class MyComponent extends React.Component {
  static propTypes = {
    ...
  };
```

**Comment by christianalfoni** [comment]
Yeah, the linter is really getting in the way of new features introduced by Babel. Will have to review and see what linting rules I have to turn off... or add rules there. Hm, have to look into it

**Comment by productiveme** [comment]
After downloading the project and changing the `webpack.config.js` ln 11-15 from

```
      "presets": [
        "stage-0",
        "es2015",
        "react"
      ]
```

to

```
      "presets": [
        "es2015",
        "react",
        "stage-0"
      ]
```

it works fine on my local machine.

**Comment by christianalfoni** [comment]
Jup, will change order on next release. Thanks a bunch for testing and giving a great error report :)

**Comment by productiveme** [comment]
Shot
