### ISSUE TITLE
Decorators syntax plugin.

### ISSUE THREAD

**Issue by idchlife** [christianalfoni/webpack-bin#68]
![image](https://cloud.githubusercontent.com/assets/4563032/13701891/e660a364-e79b-11e5-9095-6dffca94c816.png)

This makes it impossible to use decorators yet :(

Also, about plugins. Do you plan to create something like turning on or specifying different babel plugins manually in the bin?

**Comment by christianalfoni** [comment]
Hi there,

will add decorators plugin and other plugins as we move along :)

The decorator plugin was actually added, but ESLint does not recognize the syntax so removed it again. Just have to balance it correctly. Decorators will be brought back very soon :)
