### ISSUE TITLE
Better Vue.js integration

### ISSUE THREAD

**Issue by yyx990803** [christianalfoni/webpack-bin#75]
Hi, author of Vue.js here. I'm excited to see the just launched Vue boilerplate, although it could use some improvements:
1. Use Vue 1.0 instead of 0.12 (which is outdated for quite a while);
2. Integration for [vue-loader](https://github.com/vuejs/vue-loader) and ideally syntax highlighting for `*.vue` files (can simply be treated as HTML files).

I'm happy to contribute a PR if you could give me some pointers on integrating a new loader.

**Comment by christianalfoni** [comment]
No worries, this is a quick one :) Will be part of next release!

**Comment by yyx990803** [comment]
Awesome, looking forward to it! :D

**Comment by milose** [comment]
What you can do now, to quickly update Vue on premises is just type `vue` on the Configure -> Add npm package and it will pull in the newest package.

**Comment by Phunky** [comment]
:+1: was just coming to ask for vue-loader support :) looking forward to using it,

**Comment by christianalfoni** [comment]
Okay, this will be part of next release, though need to create a new boilerplate. So keep out for the release and create an issue with a BIN that uses all the new good stuff, a "Hello World" type of example :)

**Comment by christianalfoni** [comment]
Allright,

I have released new version of WebpackBin now. Could you try creating a new BIN with the deps and loaders you want? Just send me the BIN url and I will convert it to a boilerplate :)

**Comment by yyx990803** [comment]
Woohoo it works: http://www.webpackbin.com/4kMisu5al

Thank you for this great project! :D

**Comment by christianalfoni** [comment]
Great stuff! Now it loads when pointing to: "http://www.webpackbin.com/vue" :-)

**Comment by yyx990803** [comment]
Hmm, it seems the link still points to the pre-save version. Should it be persisted when I hit save?

**Comment by yyx990803** [comment]
Seems like a bug but when I open the link I posted it randomly resets to a fresh bin. Any idea?

**Comment by christianalfoni** [comment]
Ah, yeah, it does redirect you, but it should redirect you with the boilerplate of vue?

**Comment by yyx990803** [comment]
Nah, for some reason, when I create a new bin, edit it and save it, then open it again, it only shows an older version (which is not the final saved version of it)

**Comment by christianalfoni** [comment]
Ah, yeah, I deployed a new fix. Your session was gone, sorry!

Have plans for login in later release :)

**Comment by christianalfoni** [comment]
But any time, send my new url and I will update in database :)

**Comment by yyx990803** [comment]
I was probably having some cached assets issue - no matter what I edit the bin just wasn't saved. Tried again in a different browser and it worked: http://www.webpackbin.com/4y-8Oc96e

**Comment by yyx990803** [comment]
One small issue: vue-loader has a bunch of [peer dependencies](https://github.com/vuejs/vue-loader/blob/master/package.json#L45-L54), some of which are already present (e.g. babel-loader), but some are not, e.g. `vue-style-loader`. When I use a `<style>` tag inside a Vue component I get the error:

<img width="502" alt="screen shot 2016-03-22 at 4 27 59 pm" src="https://cloud.githubusercontent.com/assets/499550/13966951/1f4f934e-f04b-11e5-9825-d43ae28466e7.png">

**Comment by christianalfoni** [comment]
Ops, I installed it, but forgot to preload it. Deploying fix now. Should work in a couple of minutes :)

**Comment by yyx990803** [comment]
Yeah it's fixed now, thanks! You can use this as the new Vue boilerplate: http://www.webpackbin.com/4y-8Oc96e :D

**Comment by christianalfoni** [comment]
Okay, cool, done :)
