### ISSUE TITLE
typescript: *.tsx is not supported

### ISSUE THREAD

**Issue by Guria** [christianalfoni/webpack-bin#79]
Can't use typescript with jsx because it works only with tsx extension but webback seems treats it as js.

**Comment by christianalfoni** [comment]
Does typescript loader support jsx?

**Comment by christianalfoni** [comment]
Oh, yeah, it does :-) will add on next release

**Comment by christianalfoni** [comment]
Fixed, though there is no highlighting for .tsx that I can find. Neither CodeMirror or Ace editor

**Comment by christianalfoni** [comment]
Added issue on CodeMirror: https://github.com/codemirror/CodeMirror/issues/3893
