### ISSUE TITLE
ctrl-z "restores" content from other tabs

### ISSUE THREAD

**Issue by Guria** [christianalfoni/webpack-bin#8]
- load any boilerplate
- switch tab
- edit something
- press ctrl-z several times

content of current replaced with content of previous one

**Comment by christianalfoni** [comment]
Hm, yeah, not quite sure how to fix it yet. Might have to implement custom restore. Will keep it in mind :)

**Comment by Guria** [comment]
@christianalfoni I think textarea shouldn't be reused while tab switch. try to add file name as key prop to textarea component

**Comment by egeozcan** [comment]
I also had the same error. It should be pretty straightforward to fix with @Guria 's suggestion.

**Comment by christianalfoni** [comment]
Hm, yeah, though have to handle re-registering a codemirror instance as well. It might give "bips'n'bops" in the interface, but will try it. Thanks for the suggestion :-)

**Comment by bfitch** [comment]
I was wondering how to re-instantiate code mirror too. I think that would make the vim mode thingy work as well.

**Comment by RamonGebben** [comment]
Maybe this would be a good point to move to Ace instead of code mirror. Had better experiences with solving exactly this problem. 

We would use the `brace` package which makes it available via webpack.

**Comment by christianalfoni** [comment]
Way too much work moving to Ace, for such a small fix. There is a huge amount of linters, highlighters loaded now. And also the logic for handling code changes must be completely rewritten, which could take a lot of time :)

Will figure this one out. If we get into bigger problems we can consider Ace ;-)
