### ISSUE TITLE
http://www.webpackbin.com/ seems to be down

### ISSUE THREAD

**Issue by alterx** [christianalfoni/webpack-bin#81]
I prepared a couple of examples for a class I have to give later today but the site now appears to be down. Dunno if this is the right place to report this so feel free to point me in the right direction.

**Comment by christianalfoni** [comment]
Hi @alterx and thanks for taking time to try out the BETA. The site should not have been down today, but there is a memory error which will be fixed next week. That might have been the issue. You still having problems?

**Comment by alterx** [comment]
It's been up and down, seems to be stable now. Thanks for the quick response.
This is an awesome project BTW, looking forward to contributing :+1:

**Comment by christianalfoni** [comment]
On Sunday evening (my local time) I did a pretty major upgrade which had some issues, so was very unstable then. But should be okay now, except installing completely new packages which has a memory issue :)

Anyways, let me know how it works out! Would be really great to get a "teaching story" on the tool, as that is one of the goals. Make it a really good teaching tool :)
